import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import { useState } from 'react';
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header';
// import { BattingAvarage } from 'src/components/Functions/BattingAverage';
// import { EarnedRunAverage } from 'src/components/Functions/EarnedRunAverage';
import { useFunctionChanger } from 'src/components/hooks/ChangeFunction';


export default function Home() {
  // const [isBaShow, setIsBaShow] = useState(true);     コンポーネントを飛び出してつかっていた
  // const [isEraShow, setIsEraShow] = useState(false);
  // const FunctionChange = () => {
  //   setIsBaShow((isBaShow) => {
  //     return !isBaShow;  // true/falseを反転
  //   })
  //   setIsEraShow((isEraShow) => {
  //     return !isEraShow;
  //   })
  // }

  const { isFunction, changeFunction } = useFunctionChanger();  // フックスで対応

  return (
    <div className={styles.container}>
      <Head>
        <title>野球計算機</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}> 
      {/* .jsxの記法の制限により、return文の中でif文は使えない 
          代わりに三項演算子。nullを返すことで何も表示させないということができる
          {isBaShow ? <BattingAvarage /> : null}     ←
          {isEraShow ? <EarnedRunAverage /> : null}  ←以前までの記述

          onClick={changeFunction("ERA")}だと、 Too many re-renders. というエラーが発生するので
          アロー関数で対応*/}
      <div>
        <button onClick={() => changeFunction("BA")}>打率</button>
        <button onClick={() => changeFunction("ERA")}>防御率</button>
      </div>
        {isFunction}  
      </main>
      
      <Footer />
    </div>
  )
}
