import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header';
import { BattingAvarage } from 'src/components/BattingAverage/BattingAverage';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>野球計算機</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        {/* <Link>コンポーネント使うかも */}
        <BattingAvarage />
      </main>

      <Footer />

    </div>
  )
}
